ALTER TABLE "t_p63706319_video_sales_channel_".users
  ADD COLUMN IF NOT EXISTS shop_name VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS shop_city_code TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS shop_city_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS shop_city_guid TEXT NOT NULL DEFAULT '';